package:
  name: brian2tools
  version: "{{ load_setup_py_data().get('version') }}"

requirements:
  build:
    - python >=3.6
    - setuptools >=6.0
    - pip
  run:
    - python >=3.6
    - brian2 >=2.0
    - matplotlib >=1.3.1
    - pylems >=0.4.9
    - libneuroml
    - markdown_strings
    - lxml
test:
  # Python imports
  imports:
    - brian2tools
    - brian2tools.plotting
    - brian2tools.nmlexport
    - brian2tools.baseexport
    - brian2tools.mdexport

  commands:
    - MPLBACKEND=Agg py.test --pyargs brian2tools

  requires:
    - pytest

source:
  path: ../..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

about:
  url: https://brian2tools.readthedocs.io
  doc_url: https://brian2tools.readthedocs.io
  dev_url: https://github.com/brian-team/brian2tools/
  license: CeCILL-2.1
  license_file: LICENSE
  summary: 'Tools for the Brian 2 simulator'
