package:
  name: brian2tools
  version: "0.2.1.1"

requirements:
  build:
    - python
    - setuptools >=6.0
    - pip
  run:
    - python
    - brian2 >=2.0
    - matplotlib >=1.3.1
    - pylems >=0.4.9
    - libneuroml
    - lxml

test:
  # Python imports
  imports:
    - brian2tools
    - brian2tools.plotting
    - brian2tools.nmlexport

  commands:
    - MPLBACKEND=Agg py.test --pyargs brian2tools

  requires:
    - pytest

source:
  path: ../..

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

about:
  url: https://brian2tools.readthedocs.io
  doc_url: https://brian2tools.readthedocs.io
  dev_url: https://github.com/brian-team/brian2tools/
  license: CeCILL-2.1
  license_file: LICENSE
  summary: 'Tools for the Brian 2 simulator'
